# SQL script for creating the database

```CREATE TABLE PRODUCT (
    PRODUCT_ID             NUMBER(10) PRIMARY KEY,
    PRODUCT_NAME           VARCHAR2(30) NOT NULL,
    PACKAGE_ID             NUMBER(10),
    CURRENT_INVENTORY_COUNT NUMBER(5),
    STORE_COST             NUMBER(10,2),
    SALE_PRICE             NUMBER(10,2),
    LAST_UPDATE_DATE       DATE,
    UPDATED_BY_USER        VARCHAR2(30),
    PET_FLAG               VARCHAR2(1),
    
    CONSTRAINT FK_PRODUCT_PACKAGE
        FOREIGN KEY (PACKAGE_ID)
        REFERENCES PRODUCT(PRODUCT_ID),
        
    CONSTRAINT CHK_PRODUCT_PET_FLAG
        CHECK (PET_FLAG IN ('Y', 'N'))
);


CREATE TABLE CUSTOMER (
    CUST_ID       NUMBER(10) PRIMARY KEY,
    FIRSTNAME     VARCHAR2(20) NOT NULL,
    LASTNAME      VARCHAR2(25) NOT NULL,
    ADDRESS       VARCHAR2(32),
    CITY          VARCHAR2(20),
    STATE         VARCHAR2(2),
    ZIP           VARCHAR2(9)
);

CREATE TABLE CUSTOMER_SALE (
    SALES_ID                 NUMBER(10) PRIMARY KEY,
    CUST_ID                  NUMBER(10) NOT NULL,
    TOTAL_ITEM_AMOUNT        NUMBER(10,2),
    TAX_AMOUNT               NUMBER(10,2),
    TOTAL_SALE_AMOUNT        NUMBER(10,2),
    SALES_DATE               DATE,
    SHIPPING_HANDLING_FEE    NUMBER(5,2),
    
    CONSTRAINT FK_CUSTOMER_SALE_CUSTOMER
        FOREIGN KEY (CUST_ID)
        REFERENCES CUSTOMER(CUST_ID)
);


CREATE TABLE SALES_ITEM (
    SALES_ID       NUMBER(10) NOT NULL,
    PRODUCT_ID     NUMBER(10) NOT NULL,
    SALE_AMOUNT    NUMBER(10,2),
    
    CONSTRAINT PK_SALES_ITEM
        PRIMARY KEY (SALES_ID, PRODUCT_ID),
        
    CONSTRAINT FK_SALES_ITEM_SALE
        FOREIGN KEY (SALES_ID)
        REFERENCES CUSTOMER_SALE(SALES_ID),
        
    CONSTRAINT FK_SALES_ITEM_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID             NUMBER(10) NOT NULL,
    LOG_DATETIME           DATE NOT NULL,
    CREATED_BY_USER        VARCHAR2(30),
    LOG_TEXT               VARCHAR2(500),
    LAST_UPDATE_DATETIME   DATE,
    
    CONSTRAINT PK_PET_CARE_LOG
        PRIMARY KEY (PRODUCT_ID, LOG_DATETIME),
        
    CONSTRAINT FK_PET_CARE_LOG_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);


CREATE INDEX IDX_PRODUCT_PACKAGE_ID
    ON PRODUCT(PACKAGE_ID);

CREATE INDEX IDX_CUSTOMER_SALE_CUST_ID
    ON CUSTOMER_SALE(CUST_ID);

CREATE INDEX IDX_SALES_ITEM_PRODUCT_ID
    ON SALES_ITEM(PRODUCT_ID);

CREATE INDEX IDX_PET_CARE_LOG_PRODUCT_ID
    ON PET_CARE_LOG(PRODUCT_ID);```


# Script to add the columns required to the table PET_CARE_LOG
```ALTER TABLE PET_CARE_LOG
ADD (
    UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30)
);```

# Solution to the SQL challenge

# Trigger 1

```CREATE OR REPLACE TRIGGER trg_insert_log
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.UPDATE_DATE := SYSDATE;
    :NEW.UPDATED_BY_USER := USER;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error on insert');
END;```

# Trigger 2
```CREATE OR REPLACE TRIGGER trg_update_log
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != :OLD.UPDATED_BY_USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'You cannot update this record');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Error on update');
END;```


# Trigger 3

```CREATE OR REPLACE TRIGGER trg_delete_log
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20004, 'Only manager can delete');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20005, 'Error on delete');
END;```